{
	"_Type": "Action.Type.RestService.SendRequest",
	"OnFailure": {
		"Name": "/mdk05/Actions/GenericToastMessage.action",
		"Properties": {
			"Message": "Error"
		}
	},
	"Target": {
		"Service": "/mdk05/Services/I758675.service",
		"Path": "/completion",
		"RequestProperties": {
			"Method": "POST",
			"Headers": {
				"AI-Resource-Group": "default"
			},
			"Body": "{#Application/#ClientData/body}",
			"FetchCSRF": true
		}
	}
}